CASE_UNDEFINED = '__undefined__'
CASE_PENDING_APPROVAL = 'pending_approval'
CASE_PENDING_INVOLVEMENT = 'pending_involvement'
CASE_PARTIALLY_ASSIGNED = 'partially_assigned'
CASE_ASSIGNED = 'assigned'
CASE_PARTIALLY_COMPLETED = 'partially_completed'
CASE_COMPLETED = 'completed'
CASE_MISSING_INFO = 'missing_info'
CASE_REJECTED = 'rejected'
CASE_OVERDUE = 'overdue'
CASE_CANCELLED_BY_USER = 'cancelled_by_user'
CASE_CANCELLED_BY_ADMIN = 'cancelled_by_admin'

VALID_CASE_STATES = {CASE_PENDING_APPROVAL, CASE_PENDING_INVOLVEMENT, CASE_PARTIALLY_ASSIGNED, CASE_ASSIGNED,
                     CASE_PARTIALLY_COMPLETED, CASE_COMPLETED, CASE_CANCELLED_BY_USER, CASE_CANCELLED_BY_ADMIN,
                     CASE_MISSING_INFO, CASE_REJECTED, CASE_OVERDUE, CASE_UNDEFINED}

CASE_TRANSITIONS = dict()

CASE_TRANSITIONS[CASE_UNDEFINED] = {CASE_PENDING_APPROVAL}
CASE_TRANSITIONS[CASE_PENDING_APPROVAL] = {CASE_MISSING_INFO, CASE_REJECTED, CASE_OVERDUE, CASE_PENDING_APPROVAL,
                                           CASE_CANCELLED_BY_USER, CASE_CANCELLED_BY_ADMIN, CASE_PENDING_INVOLVEMENT}
CASE_TRANSITIONS[CASE_PENDING_INVOLVEMENT] = {CASE_PARTIALLY_ASSIGNED, CASE_ASSIGNED, CASE_OVERDUE,
                                              CASE_CANCELLED_BY_USER, CASE_CANCELLED_BY_ADMIN}
CASE_TRANSITIONS[CASE_PARTIALLY_ASSIGNED] = {CASE_ASSIGNED, CASE_OVERDUE, CASE_CANCELLED_BY_USER,
                                             CASE_CANCELLED_BY_ADMIN}
CASE_TRANSITIONS[CASE_ASSIGNED] = {CASE_PARTIALLY_COMPLETED, CASE_COMPLETED, CASE_CANCELLED_BY_USER,
                                   CASE_CANCELLED_BY_ADMIN}
CASE_TRANSITIONS[CASE_PARTIALLY_COMPLETED] = {CASE_COMPLETED, CASE_CANCELLED_BY_USER, CASE_CANCELLED_BY_ADMIN}
CASE_TRANSITIONS[CASE_COMPLETED] = set()


CASE_TRANSITIONS[CASE_MISSING_INFO] = {CASE_PENDING_APPROVAL, CASE_OVERDUE, CASE_CANCELLED_BY_USER,
                                       CASE_CANCELLED_BY_ADMIN}
CASE_TRANSITIONS[CASE_REJECTED] = {CASE_PENDING_INVOLVEMENT, CASE_CANCELLED_BY_USER, CASE_CANCELLED_BY_ADMIN}
CASE_TRANSITIONS[CASE_OVERDUE] = set()
CASE_TRANSITIONS[CASE_CANCELLED_BY_USER] = set()
CASE_TRANSITIONS[CASE_CANCELLED_BY_ADMIN] = set()

