TASK_UNDEFINED = '__undefined__'
TASK_PENDING = 'pending'
TASK_ASSIGNMENT_IN_PROCESS = 'assignment_in_process'
TASK_PENDING_USER_APPROVAL = 'pending_user_approval'
TASK_ASSIGNED = 'assigned'
TASK_CANCELLED = 'cancelled'
TASK_COMPLETED = 'completed'

VALID_TASK_STATES = {TASK_UNDEFINED, TASK_PENDING, TASK_ASSIGNMENT_IN_PROCESS, TASK_PENDING_USER_APPROVAL,
                     TASK_ASSIGNED, TASK_CANCELLED, TASK_COMPLETED}

TASK_TRANSITIONS = dict()
TASK_TRANSITIONS[TASK_UNDEFINED] = {TASK_PENDING}
TASK_TRANSITIONS[TASK_PENDING] = {TASK_ASSIGNMENT_IN_PROCESS, TASK_PENDING_USER_APPROVAL, TASK_ASSIGNED, TASK_CANCELLED}
TASK_TRANSITIONS[TASK_ASSIGNMENT_IN_PROCESS] = {TASK_ASSIGNED, TASK_PENDING, TASK_PENDING_USER_APPROVAL, TASK_CANCELLED}
TASK_TRANSITIONS[TASK_PENDING_USER_APPROVAL] = {TASK_PENDING, TASK_ASSIGNED}
TASK_TRANSITIONS[TASK_ASSIGNED] = {TASK_COMPLETED, TASK_CANCELLED, TASK_PENDING}
TASK_TRANSITIONS[TASK_CANCELLED] = set()
TASK_TRANSITIONS[TASK_COMPLETED] = set()
