TASK_TYPE_GENERAL = 'GENERAL'
TASK_TYPE_PRODUCT_REQUEST = 'PRODUCT_REQUEST'
TASK_TYPE_PRODUCT_DONATION = 'DONATION'
TASK_TYPE_PRODUCT_TRANSPORTATION = 'TRANSPORTATION'

TASK_TYPES = [TASK_TYPE_GENERAL, TASK_TYPE_PRODUCT_REQUEST, TASK_TYPE_PRODUCT_DONATION,
              TASK_TYPE_PRODUCT_TRANSPORTATION]