dry-run: null
hookfiles: "./dreddhooks.js"
language: nodejs
sandbox: false
server: node app
server-wait: 10
init: false
custom: {}
names: false
only: []
reporter: apiary
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
blueprint: docs/api-docs.md
endpoint: 'http://localhost:1337'
